#!/usr/bin/env groovy

pipeline {
    agent any
    tools {
        maven 'MAVEN-version'
    }
    stages {
        stage("init") {
            steps {
                echo "starting the application..."
            }
        }
        stage("build jar") {
            steps {
                echo "building the application..."
                sh 'mvn package'
            }
        }
        stage("build image") {
            steps {
                    echo "building the docker image..."
                    withCredentials([usernamePassword(credentialsId: 'd95e5bec-495a-49d1-90e5-3b52c8daf1a0', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                    sh 'docker build -t abdosalah663888/docker:jm1.0 .'
                    sh "echo $PASS | docker login -u $USER --password-stdin"
                    sh 'docker push abdosalah663888/docker:jm1.0'
                }
            }
        }
        stage("deploy") {
            steps {
            echo 'deploying the application...'
                }
            }
        }
    }   
}